# Generated by Django 5.1.7 on 2025-04-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='disponibilidade',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='area',
            field=models.CharField(default='Outro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cidade',
            field=models.CharField(default='São José dos Campos', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(default='Rua A, 123', max_length=255),
            preserve_default=False,
        ),
    ]
