# Generated by Django 5.1.7 on 2025-04-06 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_remove_voluntario_disponibilidade_voluntario_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
