# Generated by Django 5.1.7 on 2025-04-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_voluntario_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='criado_em',
        ),
    ]
